// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ProtocolReverse.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace ProtocolReverse {
  public static partial class gRPCService
  {
    static readonly string __ServiceName = "ProtocolReverse.gRPCService";

    static readonly grpc::Marshaller<global::ProtocolReverse.ProtocolRequest> __Marshaller_ProtocolReverse_ProtocolRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ProtocolReverse.ProtocolRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::ProtocolReverse.ProtocolReply> __Marshaller_ProtocolReverse_ProtocolReply = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::ProtocolReverse.ProtocolReply.Parser.ParseFrom);

    static readonly grpc::Method<global::ProtocolReverse.ProtocolRequest, global::ProtocolReverse.ProtocolReply> __Method_ProtocolEcho = new grpc::Method<global::ProtocolReverse.ProtocolRequest, global::ProtocolReverse.ProtocolReply>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ProtocolEcho",
        __Marshaller_ProtocolReverse_ProtocolRequest,
        __Marshaller_ProtocolReverse_ProtocolReply);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::ProtocolReverse.ProtocolReverseReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of gRPCService</summary>
    [grpc::BindServiceMethod(typeof(gRPCService), "BindService")]
    public abstract partial class gRPCServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::ProtocolReverse.ProtocolReply> ProtocolEcho(global::ProtocolReverse.ProtocolRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for gRPCService</summary>
    public partial class gRPCServiceClient : grpc::ClientBase<gRPCServiceClient>
    {
      /// <summary>Creates a new client for gRPCService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public gRPCServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for gRPCService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public gRPCServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected gRPCServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected gRPCServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::ProtocolReverse.ProtocolReply ProtocolEcho(global::ProtocolReverse.ProtocolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProtocolEcho(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::ProtocolReverse.ProtocolReply ProtocolEcho(global::ProtocolReverse.ProtocolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ProtocolEcho, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::ProtocolReverse.ProtocolReply> ProtocolEchoAsync(global::ProtocolReverse.ProtocolRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ProtocolEchoAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::ProtocolReverse.ProtocolReply> ProtocolEchoAsync(global::ProtocolReverse.ProtocolRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ProtocolEcho, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override gRPCServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new gRPCServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(gRPCServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ProtocolEcho, serviceImpl.ProtocolEcho).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, gRPCServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ProtocolEcho, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::ProtocolReverse.ProtocolRequest, global::ProtocolReverse.ProtocolReply>(serviceImpl.ProtocolEcho));
    }

  }
}
#endregion
