# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import ProtocolReverse_pb2 as ProtocolReverse__pb2


class gRPCServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProtocolEcho = channel.unary_unary(
                '/ProtocolReverse.gRPCService/ProtocolEcho',
                request_serializer=ProtocolReverse__pb2.ProtocolRequest.SerializeToString,
                response_deserializer=ProtocolReverse__pb2.ProtocolReply.FromString,
                )


class gRPCServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProtocolEcho(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_gRPCServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProtocolEcho': grpc.unary_unary_rpc_method_handler(
                    servicer.ProtocolEcho,
                    request_deserializer=ProtocolReverse__pb2.ProtocolRequest.FromString,
                    response_serializer=ProtocolReverse__pb2.ProtocolReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ProtocolReverse.gRPCService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class gRPCService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProtocolEcho(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ProtocolReverse.gRPCService/ProtocolEcho',
            ProtocolReverse__pb2.ProtocolRequest.SerializeToString,
            ProtocolReverse__pb2.ProtocolReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
