# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ProtocolReverse.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15ProtocolReverse.proto\x12\x0fProtocolReverse\"&\n\x0fProtocolRequest\x12\x13\n\x0bnumber_list\x18\x01 \x01(\x05\"$\n\rProtocolReply\x12\x13\n\x0bprotocolStr\x18\x01 \x01(\t2a\n\x0bgRPCService\x12R\n\x0cProtocolEcho\x12 .ProtocolReverse.ProtocolRequest\x1a\x1e.ProtocolReverse.ProtocolReply\"\x00\x62\x06proto3')



_PROTOCOLREQUEST = DESCRIPTOR.message_types_by_name['ProtocolRequest']
_PROTOCOLREPLY = DESCRIPTOR.message_types_by_name['ProtocolReply']
ProtocolRequest = _reflection.GeneratedProtocolMessageType('ProtocolRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLREQUEST,
  '__module__' : 'ProtocolReverse_pb2'
  # @@protoc_insertion_point(class_scope:ProtocolReverse.ProtocolRequest)
  })
_sym_db.RegisterMessage(ProtocolRequest)

ProtocolReply = _reflection.GeneratedProtocolMessageType('ProtocolReply', (_message.Message,), {
  'DESCRIPTOR' : _PROTOCOLREPLY,
  '__module__' : 'ProtocolReverse_pb2'
  # @@protoc_insertion_point(class_scope:ProtocolReverse.ProtocolReply)
  })
_sym_db.RegisterMessage(ProtocolReply)

_GRPCSERVICE = DESCRIPTOR.services_by_name['gRPCService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PROTOCOLREQUEST._serialized_start=42
  _PROTOCOLREQUEST._serialized_end=80
  _PROTOCOLREPLY._serialized_start=82
  _PROTOCOLREPLY._serialized_end=118
  _GRPCSERVICE._serialized_start=120
  _GRPCSERVICE._serialized_end=217
# @@protoc_insertion_point(module_scope)
